# Generated by Django 5.0 on 2024-01-22 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapperApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmapping',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
