# Generated by Django 5.0 on 2024-01-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapperApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapping',
            name='fullURL',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='urlmapping',
            name='urlKey',
            field=models.TextField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
