# Generated by Django 5.0 on 2024-01-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapperApp', '0002_alter_urlmapping_fullurl_alter_urlmapping_urlkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapping',
            name='fullURL',
            field=models.URLField(),
        ),
    ]
